export const SYNC_CONFIG = {
  SOFT_THRESHOLD_MS: 500,
  HARD_THRESHOLD_MS: 2500,
  HARD_SEEK_COOLDOWN_MS: 8000,
  SOFT_CORRECTION_WINDOW_S: 8,
  SOFT_CORRECTION_MIN_DELTA: 0.03,
  SOFT_CORRECTION_MAX_DELTA: 0.15,
  BUFFERING_CAP_MS: 10000,
} as const;
